Repository Algo-Phantoms/Algo-Phantoms-Frontend, pull requests merged in 2021-03, with the labels that each got.

#93 Added opportunities link in features
  index.html
Labels: gssoc21, level1

#129 Added a simple workflow to greet user on opening a issue!
  .github/workflows/greet.yml
Labels: enhancement, gssoc21, level2

#114 Social_Media_Sidebar #issue68
  css/style.css
  index.html
Labels: enhancement, gssoc21, level3

#162 added back to top button team.html
  index.html
  js/index.js
  team.html
Labels: UI/UX, gssoc21, level2

#76 issue #72 - modified the main head and contact button
  css/style.css
  index.html
Labels: bug, changes requested, gssoc21, level2

#165 added target=_blank to all hyperlinks (issue 154)
  index.html
  team.html
Labels: enhancement, gssoc21, level2

#163 Update github icon color in the footer.
  index.html
  team.html
Labels: UI/UX, changes requested, gssoc21, level2

#184 Fixed issue #174
  team.html
Labels: UI/UX, bug, gssoc21, level2

#186 🚀[Feat]: Pull Request Template Added
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, gssoc21, level1

#98 Animation to About us Section
  css/style.css
  index.html
Labels: UI/UX, enhancement, gssoc21, level3

#84 added issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: gssoc21, level2

#123 Added the SiteMaps
  css/sitemapStyles.css
  index.html
  sitemap.html
  sitemap.xml
  team.html
Labels: SEO, gssoc21, level2

#210 centralized home content in mobile view
  css/style.css
Labels: UI/UX, bug, gssoc21

#238 nav bar adjusted
  css/style.css
Labels: GSSOC21, bug, level1

#234 Changed the color of scroll bar
  css/style.css
Labels: GSSOC21, Good first issue, UI/UX, enhancement, level2

#66 fix Heading text align Properly
  css/style.css
Labels: GSSOC21, bug, level1

#224 Modified the button on DSA page
  DSA.html
Labels: GSSOC21, enhancement, level2

#275 styling of dropdown menu
  css/style.css
Labels: GSSOC21, UI/UX, level1

#241 Improved the footer padding
  css/style.css
  team.html
Labels: GSSOC21, UI/UX, bug, level1

#235 issue #13 Fixed:"Back to top" button should not be displayed when we …
  css/style.css
  js/index.js
Labels: GSSOC21, bug, level1

#227 click issue in features section is done
  index.html
Labels: GSSOC21, bug, level2

#43 Contact Button&Link update
  index.html
Labels: changes requested

#293 Issue 251 align navbar
  css/style.css
  index.html
  team.html
Labels: GSSOC21, Good first issue, bug, level0

#286 Added required favicon files
  DSA.html
  favicon_package/android-chrome-192x192.png
  favicon_package/apple-touch-icon.png
  favicon_package/browserconfig.xml
  favicon_package/favicon-16x16.png
  favicon_package/favicon-32x32.png
  favicon_package/favicon.ico
  favicon_package/mstile-150x150.png
  favicon_package/safari-pinned-tab.svg
  favicon_package/site.webmanifest
  index.html
  practicedsa.html
  sitemap.html
  team.html
Labels: GSSOC21, enhancement, level1

#297 Click issue in Features section Our team Page is done
  team.html
Labels: GSSOC21, bug, level1
