Repository Algo-Phantoms/Algo-Phantoms-Frontend, pull requests merged in 2021-04, with the labels that each got.

#137 Added teams section carousel in the home page.
  css/style.css
  index.html
Labels: GSSOC21, enhancement, level3

#318 [navbar]improved navbar
  css/style.css
  index.html
  team.html
Labels: GSSOC21, UI/UX, level1

#280 Project Ideas dropdown section added
  index.html
  team.html
Labels: GSSOC21, enhancement, level0

#285 Made changes in the Team Cards UI
  css/style.css
  team.html
Labels: GSSOC21, UI/UX, enhancement, level2

#348 [Footer Updated] Footer Updated again.
  DSA.html
  index.html
  practicedsa.html
Labels: GSSOC21, enhancement, level2

#339 Added FAQ section
  css/style.css
  index.html
  js/index.js
Labels: changes requested

#306 BookList #Issue222 New pr
  booklist.html
  css/bookliststyle.css
  images/book_background.jpg
  index.html
Labels: GSSOC21, enhancement, level3

#335 Aligned the contents of the navbar in the center
  css/style.css
  index.html
  team.html
Labels: changes requested

#239 Validated HTML
  index.html
  team.html
Labels: GSSOC21, changes requested, level2

#364 Modified
  css/style.css
  index.html
  js/typing.js
Labels: GSSOC21, level1

#382 Added arrows to the scrollbar
  css/style.css
  images/downarrow.png
  images/uparrow.png
Labels: GSSOC21, level1

#408 Fixed the social icons in the footer of all the webpages
  css/style.css
Labels: GSSOC21, enhancement, level0

#396 UI links
  index.html
Labels: GSSOC21, bug, level0

#393 Updated style.css to overcome the overlapping of the social-sidebar on all the elements of home page
  css/style.css
Labels: GSSOC21, level2

#435 Removed the social media sidebar from home page in phone view
  css/style.css
Labels: GSSOC21, bug, level1

#425 Updated index.js to close navbar when clicked on a link for all pages
  js/index.js
Labels: GSSOC21, UI/UX, bug, level1

#433 added an image to the about us section
  css/style.css
  images/about_us_background.jpg
  index.html
Labels: GSSOC21, enhancement, level1

#448 Github link added
  index.html
Labels: GSSOC21, bug, level1

#412 nav bar added
  DSA.html
  css/style.css
  practicedsa.html
Labels: GSSOC21, level2

#410 changed hr tag
  css/style.css
  index.html
Labels: GSSOC21, UI/UX, bug, level1

#455 Made dsa.html responsive
  DSA.html
Labels: changes requested

#445 Added links to skills section and enhanced them
  index.html
Labels: changes requested

#452 Updating footer
  booklist.html
  team.html
Labels: GSSOC21, bug, level2

#398 added id to the navbar
  css/style.css
  index.html
  team.html
Labels: GSSOC21, bug, level1

#430 Faq section aligned and styled in mobile view
  css/style.css
  index.html
Labels: GSSOC21, bug, changes requested, level2
