Repository Algo-Phantoms/Algo-Phantoms-Frontend, pull requests merged in 2021-05, with the labels that each got.

#458 text overlapping problem solved
  css/style.css
  index.html
Labels: GSSOC21, bug, level2

#465 Updated Navbar of teams page. Fixes #365
  team.html
Labels: GSSOC21, bug, level1

#469 corrected links
  css/style.css
Labels: GSSOC21, UI/UX, enhancement, level1

#384 Added navbar in booklist.html
  booklist.html
Labels: GSSOC21, UI/UX, changes requested, enhancement, level3

#472 fixed the typographical errors on subheading of homepage
  index.html
Labels: GSSOC21, documentation, level0

#475 Fixed Image and data not being hidden on page flip in team.html in Firefox browser
  css/style.css
Labels: changes requested

#482 added a logo in the team page
  css/style.css
  images/team logo2.png
  team.html
Labels: GSSOC21, enhancement, level2

#481 Custom scollbar for firefox
  css/style.css
Labels: GSSOC21, bug, level2

#486 banner is aligned
  css/style.css
Labels: GSSOC21, Good first issue, enhancement, level1

#492 Center aligned the hover in booklist.html
  css/bookliststyle.css
Labels: GSSOC21, UI/UX, bug, level1

#493 Center aligned footer section in mobile view.
  css/bookliststyle.css
  css/style.css
Labels: GSSOC21, UI/UX, bug, level1

#494 404 error page added
  404.html
  css/style.css
  images/8.-Error-404.png
Labels: changes requested

#496 improved responsiveness
  css/style.css
  index.html
Labels: GSSOC21, UI/UX, level2

#504 'more' option in navbar expand on hovering
  css/style.css
Labels: GSSOC21, enhancement, level0

#505 skill section enhanced
  css/style.css
  index.html
Labels: GSSOC21, enhancement, level2

#503 Added space
  index.html
Labels: GSSOC21, bug, level0

#512 update in team.html
  team.html
Labels: GSSOC21, level0

#509 Added Effects in styling of FAQ Section ! #466
  css/style.css
  index.html
Labels: GSSOC21, level2

#460 Added contact us page
  contact.html
  css/style.css
  index.html
Labels: changes requested

#524 Added 'which' in the contact description
  index.html
Labels: GSSOC21, bug, level0

#527 Added option of suggested books in navbar of DSA.html
  DSA.html
Labels: GSSOC21, bug, level1

#498 Coding site
  DSA.html
  booklist.html
  css/style.css
  index.html
  practicedsa.html
  suggested_coding_site.html
  team.html
Labels: changes requested

#528 Made navbar of practicedsa.html same as other pages
  practicedsa.html
Labels: GSSOC21, bug, level1

#531 Synced and changed the color
  team.html
Labels: GSSOC21, UI/UX, enhancement, level0

#535 Made the 'Sharpen your skills' heading look same #532 resolved
  css/style.css
  index.html
Labels: GSSOC21, bug, level1

#541 Margin Update #537
  booklist.html
  css/style.css
  index.html
Labels: GSSOC21, bug, level2

#542 FAQ updated #539
  booklist.html
  index.html
Labels: GSSOC21, documentation, level1
